spring:
  application:
    name: utils
logging:
  level:
    root: info
  config: classpath:logback-config.xml
  file:
    path: /tmp/logs

elk:
  logstash:
    print:
      enable: 1
    host: localhost:8065